In [11]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

add = array1 + array2
subtract = array1 - array2
multiply = array1 * array2
divide = array1 / array2

In [13]:
add

array([11, 22, 33, 44, 55])

In [15]:
subtract

array([ -9, -18, -27, -36, -45])

In [17]:
multiply

array([ 10,  40,  90, 160, 250])

In [19]:
divide

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [28]:
array3 = np.array(range(1, 21))

In [30]:
array3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
array3[:5]

array([1, 2, 3, 4, 5])

In [36]:
array3[-5:]

array([16, 17, 18, 19, 20])

In [40]:
array3[array3 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [42]:
array3[array3 % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [44]:
array3[array3 > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [102]:
import pandas as pd 

# Criando o DataFrame
dados = {
    "Entregador": ["Narciso", "João Paulo", "Lucas", "Passoca", "Guilherme"],
    "Distância_km": [12.5, 8.3, 15.0, 6.2, 10.1],
    "Valor_pago": [9.2, 6.5, 11, 4.8, 7.9]
}

df = pd.DataFrame(dados)

# Mostrando o DataFrame
print(df)

   Entregador  Distância_km  Valor_pago
0     Narciso          12.5         9.2
1  João Paulo           8.3         6.5
2       Lucas          15.0        11.0
3     Passoca           6.2         4.8
4   Guilherme          10.1         7.9


In [104]:
dados["Entregador"]

['Narciso', 'João Paulo', 'Lucas', 'Passoca', 'Guilherme']

In [106]:
df[df["Valor_pago"] > 8]

Entregador  Distância_km  Valor_pago
0    Narciso          12.5         9.2
2      Lucas          15.0        11.0

In [108]:
df["Distância_km"].mean()

10.42

In [114]:
media_distancia = df["Distância_km"].mean()
df[df["Distância_km"] > media_distancia][["Entregador", "Distância_km"]]


Entregador  Distância_km
0    Narciso          12.5
2      Lucas          15.0

In [124]:
media_distancia = df["Distância_km"].mean()
df[(df["Distância_km"] < media_distancia) & (df["Valor_pago"] < 8)][["Entregador", "Distância_km"]]


Entregador  Distância_km
1  João Paulo           8.3
3     Passoca           6.2
4   Guilherme          10.1

########################################################
########################################################
########################################################
########################################################
########################################################

In [126]:
import pandas as pd

dados = {
    "Entregador": ["Carlos", "Marina", "João", "Ana"],
    "Corridas": [12, 15, 10, 20],
    "Nota Média": [4.7, 4.0, 4.6, 4.8]
}

df = pd.DataFrame(dados)
df.index = ["A", "B", "C", "D"] # Índices personalizados

print(df)

  Entregador  Corridas  Nota Média
A     Carlos        12         4.7
B     Marina        15         4.0
C       João        10         4.6
D        Ana        20         4.8


In [146]:
df.loc["B"]

Entregador    Marina
Corridas          15
Nota Média       4.0
Name: B, dtype: object

In [148]:
df.iloc[2]["Nota Média"]

4.6

In [162]:
df[["Entregador", "Nota Média"]]

Entregador  Nota Média
A     Carlos         4.7
B     Marina         4.0
C       João         4.6
D        Ana         4.8

In [174]:
df[df["Nota Média"] >= 4.7]

Entregador  Corridas  Nota Média
A     Carlos        12         4.7
D        Ana        20         4.8

In [178]:
df["Eficiência"] = df["Nota Média"] / df["Corridas"]
df

Entregador  Corridas  Nota Média  Eficiência
A     Carlos        12         4.7    0.391667
B     Marina        15         4.0    0.266667
C       João        10         4.6    0.460000
D        Ana        20         4.8    0.240000

In [184]:
df["Eficiência"].mean()

0.3395833333333333

In [186]:
df[df["Eficiência"] > df["Eficiência"].mean()]

Entregador  Corridas  Nota Média  Eficiência
A     Carlos        12         4.7    0.391667
C       João        10         4.6    0.460000

In [192]:
import numpy as np

condicoes = [
    df["Eficiência"] >= 0.4,
    (df["Eficiência"] >= 0.3) & (df["Eficiência"] < 0.4),
    df["Eficiência"] < 0.3
]

resultados = ["Excelente", "Bom", "Regular"]

df["Desempenho"] = np.select(condicoes, resultados)
df[["Entregador", "Eficiência", "Desempenho"]]

Entregador  Eficiência Desempenho
A     Carlos    0.391667        Bom
B     Marina    0.266667    Regular
C       João    0.460000  Excelente
D        Ana    0.240000    Regular

In [196]:
import numpy as np

matriz = np.array([
    [2, 4],
    [3, 5],
    [6, 7]
])

In [206]:
transposta = matriz.T
print(transposta)

[[2 3 6]
 [4 5 7]]


In [27]:
import numpy as np
np.set_printoptions(precision=2, floatmode='fixed')  # Formatação fixa com 2 casas decimais
notas = np.array([
    [4.7, 4.5, 4.8],   # Carlos
    [4.0, 3.9, 4.1],   # Marina
    [4.6, 4.7, 4.5],   # João
    [4.9, 4.8, 4.7]    # Ana
])

In [29]:
media_por_entregador = notas.mean(axis=1)
print("Média por entregador:", np.round(media_por_entregador, 2))

Média por entregador: [4.67 4.00 4.60 4.80]


In [13]:
media_por_avaliacao = notas.mean(axis=0)
print("Média por avaliação", media_por_avaliacao)

Média por avaliação [4.55  4.475 4.525]


In [15]:
maior_por_entregador = notas.max(axis=1)
print("Maior nota por entregador", maior_por_entregador)

Maior nota por entregador [4.8 4.1 4.7 4.9]


In [17]:
menor_por_avaliacao = notas.min(axis=0)
print("Menor nota por avaliação", notas.min(axis=0))

Menor nota por avaliação [4.  3.9 4.1]


In [31]:
import pandas as pd

df = pd.DataFrame({
    "Entregador": ["Carlos", "Marina", "João", "Ana", "Lucas"],
    "Corridas": [12, 15, 10, 20, 9],
    "Nota Média": [4.7, 4.0, 4.6, 4.8, 3.9],
    "Eficiência": [0.39, 0.27, 0.46, 0.24, 0.43]
})

In [45]:
df[(df["Corridas"] > 10) & (df["Eficiência"] > 0.3)]


Entregador  Corridas  Nota Média  Eficiência
0     Carlos        12         4.7        0.39

In [47]:
df.iloc[-2:]

Entregador  Corridas  Nota Média  Eficiência
3        Ana        20         4.8        0.24
4      Lucas         9         3.9        0.43

In [61]:
df.tail(-2)

Entregador  Corridas  Nota Média  Eficiência
2       João        10         4.6        0.46
3        Ana        20         4.8        0.24
4      Lucas         9         3.9        0.43

In [63]:
import pandas as pd

df = pd.DataFrame({
    "Entregador": ["Carlos", "Marina", "João", "Ana", "Lucas", "Guilherme"],
    "Cidade": ["Porto", "Lisboa", "Porto", "Lisboa", "Braga", "Braga"],
    "Corridas": [12, 15, 10, 20, 9, 11],
    "Nota Média": [4.7, 4.0, 4.6, 4.8, 3.9, 4.3]
})

df

Entregador  Cidade  Corridas  Nota Média
0     Carlos   Porto        12         4.7
1     Marina  Lisboa        15         4.0
2       João   Porto        10         4.6
3        Ana  Lisboa        20         4.8
4      Lucas   Braga         9         3.9
5  Guilherme   Braga        11         4.3

In [77]:
df.groupby("Cidade")["Nota Média"].mean()

Cidade
Braga     4.10
Lisboa    4.40
Porto     4.65
Name: Nota Média, dtype: float64

In [79]:
df.groupby("Cidade")["Corridas"].sum()

Cidade
Braga     20
Lisboa    35
Porto     22
Name: Corridas, dtype: int64

In [83]:
df["Cidade"].value_counts()

Cidade
Porto     2
Lisboa    2
Braga     2
Name: count, dtype: int64

In [85]:
print(df["Cidade"].value_counts())

Cidade
Porto     2
Lisboa    2
Braga     2
Name: count, dtype: int64


In [89]:
df.groupby("Cidade").size()

Cidade
Braga     2
Lisboa    2
Porto     2
dtype: int64

In [ ]:
####
####
####
####

In [93]:
import pandas as pd
import numpy as np

# Criando dois DataFrames
df1 = pd.DataFrame(
    np.arange(9.).reshape(3, 3),
    columns=list("bcd"),
    index=["João", "Maria", "Carlos"]
)

df2 = pd.DataFrame(
    np.arange(12.).reshape(4, 3),
    columns=list("bce"),
    index=["Maria", "Carlos", "Ana", "Lucas"]
            )
print("df1:\n", df1)
print("\ndf2:\n", df2)

# Operação entre eles
resultado = df1 + df2
print("\nResultado da soma: \n", resultado)

df1:
           b    c    d
João    0.0  1.0  2.0
Maria   3.0  4.0  5.0
Carlos  6.0  7.0  8.0

df2:
           b     c     e
Maria   0.0   1.0   2.0
Carlos  3.0   4.0   5.0
Ana     6.0   7.0   8.0
Lucas   9.0  10.0  11.0

Resultado da soma: 
           b     c   d   e
Ana     NaN   NaN NaN NaN
Carlos  9.0  11.0 NaN NaN
João    NaN   NaN NaN NaN
Lucas   NaN   NaN NaN NaN
Maria   3.0   5.0 NaN NaN


In [140]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame([
    [20, 70, 90],
    [50, 60, 50],
    [70, 80, 90]
], columns=["Prova1", "Prova2", "Prova3"], index=["Arbor", "Narciso", "Monday"])

df2 = pd.DataFrame([
    [55, 60, 75],
    [40, 50, 60]
], columns=["Prova1", "Prova2", "Prova3"], index=["Narciso", "Lucas"])

df1.add(df2, fill_value=0)

Prova1  Prova2  Prova3
Arbor      20.0    70.0    90.0
Lucas      40.0    50.0    60.0
Monday     70.0    80.0    90.0
Narciso   105.0   120.0   125.0

In [136]:
df1 + df2

Prova1  Prova2  Prova3
Arbor       NaN     NaN     NaN
Lucas       NaN     NaN     NaN
Monday      NaN     NaN     NaN
Narciso   105.0   120.0   125.0

In [210]:
import pandas as pd
import numpy  as np

dados = [
    {"Nome": "Carlos", "Nota1": 8.5, "Nota2": None, "Nota3": 9.0},
    {"Nome": "Marina", "Nota1": 9.0, "Nota2": 8.0, "Nota3": None},
    {"Nome": "João", "Nota1": None, "Nota2": 7.5, "Nota3": 8.0},
    {"Nome": "Ana", "Nota1": 7.5, "Nota2": 8.5, "Nota3": None},
    {"Nome": "Lucas", "Nota1": 6.0, "Nota2": None, "Nota3": 6.5},
]

df = pd.DataFrame(dados)
df

Nome  Nota1  Nota2  Nota3
0  Carlos    8.5    NaN    9.0
1  Marina    9.0    8.0    NaN
2    João    NaN    7.5    8.0
3     Ana    7.5    8.5    NaN
4   Lucas    6.0    NaN    6.5

In [212]:
df.isna()

Nome  Nota1  Nota2  Nota3
0  False  False   True  False
1  False  False  False   True
2  False   True  False  False
3  False  False  False   True
4  False  False   True  False

In [215]:
df = df.fillna(0)

In [217]:
df

Nome  Nota1  Nota2  Nota3
0  Carlos    8.5    0.0    9.0
1  Marina    9.0    8.0    0.0
2    João    0.0    7.5    8.0
3     Ana    7.5    8.5    0.0
4   Lucas    6.0    0.0    6.5

In [253]:
import pandas as pd

df = pd.DataFrame({
    "Nome": ["Carlos", 'Marina', 'João', 'Ana', 'Lucas'],
    'Frase': [
        'Gosto de pandas',
        'Estou aprendendo python', 
        'Python é divertido',
        'Não gosto de pandas', 
        'Amo programar'
    ]
})

df

Nome                    Frase
0  Carlos          Gosto de pandas
1  Marina  Estou aprendendo python
2    João       Python é divertido
3     Ana      Não gosto de pandas
4   Lucas            Amo programar

In [255]:
df['Frase'].str.upper()

0            GOSTO DE PANDAS
1    ESTOU APRENDENDO PYTHON
2         PYTHON É DIVERTIDO
3        NÃO GOSTO DE PANDAS
4              AMO PROGRAMAR
Name: Frase, dtype: object

In [257]:
df['Frase'].str.contains('pandas')

0     True
1    False
2    False
3     True
4    False
Name: Frase, dtype: bool

In [259]:
df['Frase'].str.replace('pandas', "Cachorros", regex=False)

0         Gosto de Cachorros
1    Estou aprendendo python
2         Python é divertido
3     Não gosto de Cachorros
4              Amo programar
Name: Frase, dtype: object

In [261]:
df['Frase'].str.len()

0    15
1    23
2    18
3    19
4    13
Name: Frase, dtype: int64

In [263]:
df[~df['Frase'].str.contains('pandas')]

Nome                    Frase
1  Marina  Estou aprendendo python
2    João       Python é divertido
4   Lucas            Amo programar

In [278]:
df['frase_corrigida'] = df['Frase'].str.replace('pandas', "gatos", regex=False)
df

Nome                    Frase          frase_corrigida
0  Carlos          Gosto de pandas           Gosto de gatos
1  Marina  Estou aprendendo python  Estou aprendendo python
2    João       Python é divertido       Python é divertido
3     Ana      Não gosto de pandas       Não gosto de gatos
4   Lucas            Amo programar            Amo programar

In [284]:
df[df['Frase'].str.startswith('Python')]

Nome               Frase     frase_corrigida
2  João  Python é divertido  Python é divertido

In [ ]:
####
####
####
####

In [286]:
import pandas as pd
import numpy  as np

dados = [
    {"Entregador": "Carlos", "Cidade": 'Porto', "Corridas": 12, "Nota Média": 4.7},
    {"Entregador": "Marina", "Cidade": 'Lisboa', "Corridas": 15, "Nota Média": 4.0},
    {"Entregador": "João", "Cidade": 'Porto', "Corridas": 10, "Nota Média": 4.6},
    {"Entregador": "Ana", "Cidade": 'Lisboa', "Corridas": 20, "Nota Média": 4.8},
    {"Entregador": "Lucas", "Cidade": 'Braga', "Corridas": 9, "Nota Média": 3.9},
    {"Entregador": "Lucas", "Cidade": 'Braga', "Corridas": 11, "Nota Média": 4.3},

]

df = pd.DataFrame(dados)
df

Entregador  Cidade  Corridas  Nota Média
0     Carlos   Porto        12         4.7
1     Marina  Lisboa        15         4.0
2       João   Porto        10         4.6
3        Ana  Lisboa        20         4.8
4      Lucas   Braga         9         3.9
5      Lucas   Braga        11         4.3

In [295]:
df['Cidade'] = df['Cidade'].astype('category')

In [297]:
df.dtypes

Entregador      object
Cidade        category
Corridas         int64
Nota Média     float64
dtype: object

In [302]:
df[df['Cidade'] == 'Porto']

Entregador Cidade  Corridas  Nota Média
0     Carlos  Porto        12         4.7
2       João  Porto        10         4.6

In [308]:
df[df['Nota Média'] > 4.5 ]

Entregador  Cidade  Corridas  Nota Média
0     Carlos   Porto        12         4.7
2       João   Porto        10         4.6
3        Ana  Lisboa        20         4.8

In [ ]:
####
####
####
####

In [3]:
import pandas as pd

dados = [
    {"Entregador": "Carlos", "Nota": 4.7},
    {"Entregador": "Marina", "Nota": 4.0},
    {"Entregador": "Carlos", "Nota": 4.7},
    {"Entregador": "João", "Nota": 4.6},
    {"Entregador": "Ana", "Nota": 4.8},
    {"Entregador": "Marina", "Nota": 4.0}
]
df = pd.DataFrame(dados)
df 

Entregador  Nota
0     Carlos   4.7
1     Marina   4.0
2     Carlos   4.7
3       João   4.6
4        Ana   4.8
5     Marina   4.0

In [7]:
df.drop_duplicates()

Entregador  Nota
0     Carlos   4.7
1     Marina   4.0
3       João   4.6
4        Ana   4.8

In [17]:
df['Nota Ajustada'] = df['Nota'].apply(lambda x: x + 0.1)

In [27]:
df

Entregador  Nota  Nota Ajustada
0     Carlos   4.7            4.8
1     Marina   4.0            4.1
2     Carlos   4.7            4.8
3       João   4.6            4.7
4        Ana   4.8            4.9
5     Marina   4.0            4.1

In [29]:
import numpy as np

condicoes = [
    df["Nota"] >= 4.6,
    (df["Nota"] >= 4.0) & (df["Nota"] < 4.5),
    df["Nota"] < 4.0
]

resultados = ["Excelente", "Boa", "Regular"]

df["Avaliação"] = np.select(condicoes, resultados)
df[["Entregador", "Nota", "Avaliação"]]

Entregador  Nota  Avaliação
0     Carlos   4.7  Excelente
1     Marina   4.0        Boa
2     Carlos   4.7  Excelente
3       João   4.6  Excelente
4        Ana   4.8  Excelente
5     Marina   4.0        Boa

In [31]:
def classificar_nota(nota):
    if nota >= 4.6:
        return "Excelente"
    elif nota >= 4.0:
        return 'Boa'
    else: 
        return 'Regular'

df['Avaliação'] = df['Nota'].apply(classificar_nota)
df[['Entregador', 'Nota', 'Avaliação']]

Entregador  Nota  Avaliação
0     Carlos   4.7  Excelente
1     Marina   4.0        Boa
2     Carlos   4.7  Excelente
3       João   4.6  Excelente
4        Ana   4.8  Excelente
5     Marina   4.0        Boa

In [45]:
import pandas as pd

dados = [
    {'Entregador': 'Carlos', 'Nota': 4.7},
    {'Entregador': 'Marina', 'Nota': 4.0},
    {'Entregador': 'Carlos', 'Nota': 4.7},
    {'Entregador': 'João', 'Nota': 4.6},
    {'Entregador': 'Ana', 'Nota': 4.8},
    {'Entregador': 'Marina', 'Nota': 4.0}
]

df = pd.DataFrame(dados)

In [47]:
df.sort_values('Nota', ascending=False)

Entregador  Nota
4     Ana     4.8 
0  Carlos     4.7 
2  Carlos     4.7 
3    João     4.6 
1  Marina     4.0 
5  Marina     4.0

In [49]:
df.sort_values(by=['Nota', 'Entregador'], ascending=[False, True])

Entregador  Nota
4     Ana     4.8 
0  Carlos     4.7 
2  Carlos     4.7 
3    João     4.6 
1  Marina     4.0 
5  Marina     4.0

In [51]:
df.drop_duplicates()

Entregador  Nota
0  Carlos     4.7 
1  Marina     4.0 
3    João     4.6 
4     Ana     4.8

In [53]:
df.sort_values('Nota')

Entregador  Nota
1  Marina     4.0 
5  Marina     4.0 
3    João     4.6 
0  Carlos     4.7 
2  Carlos     4.7 
4     Ana     4.8

In [55]:
df = df.drop_duplicates().copy()

In [57]:
df

Entregador  Nota
0  Carlos     4.7 
1  Marina     4.0 
3    João     4.6 
4     Ana     4.8

    ####
        ####
            ####
                ####

In [70]:
df['Nota Ajustada'] = df['Nota'] + 0.2

KeyError: 'Nota'

In [62]:
df

Entregador  Nota  Nota Ajustada
0  Carlos     4.7   4.9          
1  Marina     4.0   4.2          
3    João     4.6   4.8          
4     Ana     4.8   5.0

In [68]:
import numpy as np

condicoes = [
    df['Nota Ajustada'] >= 4.8,
    (df["Nota Ajustada"] >= 4.0) & (df['Nota Ajustada'] < 4.5),
     df['Nota Ajustada'] < 4.0
]

resultados = ['Excelente', 'Boa', 'Regular']

df['Classificação'] = np.select(condicoes, resultados)
df[['Entregador', 'Nota', 'Classificação']]

KeyError: 'Nota Ajustada'

In [66]:
import pandas as pd

df = pd.DataFrame({
    'Nome': ['Carlos', 'Ana', 'João'],
    'Idade': [25, 22, 28],
    'Nota Final': [8.5, 9.0, 7.5],
})

df_renomeado = df.rename(columns={"Nota Final": 'Nota'})

df_renomeado = df_renomeado.rename(index={0: 'A', 1: 'B', 2: 'C'})

df_renomeado

Nome     Idade  Nota
A  Carlos  25     8.5 
B     Ana  22     9.0 
C    João  28     7.5

In [105]:
df_sem_idade = df_renomeado.drop(columns=["Idade"])

df_sem_linha_b = df_renomeado.drop(index=['B'])


Nome  Idade  Nota Final
0  Carlos     25         8.5
1     Ana     22         9.0
2    João     28         7.5

In [107]:
df_sem_idade

Nome  Nota
A  Carlos   8.5
B     Ana   9.0
C    João   7.5

In [119]:
df.sort_index(axis=1)

Idade    Nome  Nota Final
0     25  Carlos         8.5
1     22     Ana         9.0
2     28    João         7.5

In [121]:
import pandas as pd

df = pd.DataFrame({
    'Nome': ['Carlos', 'Ana', 'Carlos', 'João', 'Ana', 'Carlos'],
    'Idade': [25, 22, 25, 28, 23, 25],
    'Nota': [8.5, 9.0, 8.5, 7.5, 9.0, 8.5]
})

In [123]:
df

Nome  Idade  Nota
0  Carlos     25   8.5
1     Ana     22   9.0
2  Carlos     25   8.5
3    João     28   7.5
4     Ana     23   9.0
5  Carlos     25   8.5

In [133]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [135]:
df.duplicated(subset=['Nome', 'Idade'])

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [169]:
import pandas as pd

df = pd.DataFrame({
    'Nome': ['Carlos', 'Ana', 'Carlos', 'João', 'Ana', 'Carlos'],
    'Nota': [8.5, 9.0, 8.5, 7.5, 9.0, 8.5]
})

df

Nome  Nota
0  Carlos   8.5
1     Ana   9.0
2  Carlos   8.5
3    João   7.5
4     Ana   9.0
5  Carlos   8.5

In [173]:
df['Nome'].unique()

array(['Carlos', 'Ana', 'João'], dtype=object)

In [175]:
df['Nome'].nunique()

3

In [177]:
df['Nome'].value_counts()

Nome
Carlos    3
Ana       2
João      1
Name: count, dtype: int64

In [29]:
import pandas as pd

dados = ({
    'Nome': ['Narciso', 'João', 'Passoca', 'Guilherme', 'Lucas'],
    'Idade': [27, 24, 23, 24, 19],
    'Ocupação': ['Estafeta', 'Técnico em eletrônica', 'Programador', 'Programador', 'Estudante']
})

df = pd.DataFrame(dados)

df

Nome        Idade Ocupação              
0    Narciso  27                  Estafeta
1       João  24     Técnico em eletrônica
2    Passoca  23               Programador
3  Guilherme  24               Programador
4      Lucas  19                 Estudante

In [1]:
import pandas as pd

dados = {
    'Nome': ['Ana', 'Bruno', 'Carla', 'Vadisnelson', 'Clebisvaldo', 'Sindicreia', 'Margarida'],
    'Idade': [23, 31, 27, 32, 45, 29, 18],
    'Nota': [8.5, 7.2, 9.1, 7.0, 8.2, 5.0, 10],
}

df = pd.DataFrame(dados)
df

Nome  Idade  Nota
0          Ana     23   8.5
1        Bruno     31   7.2
2        Carla     27   9.1
3  Vadisnelson     32   7.0
4  Clebisvaldo     45   8.2
5   Sindicreia     29   5.0
6    Margarida     18  10.0

In [3]:
df[df['Nota'] > 8]

Nome  Idade  Nota
0          Ana     23   8.5
2        Carla     27   9.1
4  Clebisvaldo     45   8.2
6    Margarida     18  10.0

In [8]:
import numpy as np

condicoes = [
    df['Nota'] >= 9,
    (df['Nota'] >= 8) & (df['Nota'] < 9),
    df['Nota'] < 8
]
resultados = ['Excelente', 'Bom', 'Ridículo']

df['Situação'] = np.select(condicoes, resultados)
df

Nome  Idade  Nota   Situação
0          Ana     23   8.5        Bom
1        Bruno     31   7.2   Ridículo
2        Carla     27   9.1  Excelente
3  Vadisnelson     32   7.0   Ridículo
4  Clebisvaldo     45   8.2        Bom
5   Sindicreia     29   5.0   Ridículo
6    Margarida     18  10.0  Excelente

In [14]:
df.sort_values('Nota', ascending=False)

Nome  Idade  Nota   Situação
6    Margarida     18  10.0  Excelente
2        Carla     27   9.1  Excelente
0          Ana     23   8.5        Bom
4  Clebisvaldo     45   8.2        Bom
1        Bruno     31   7.2   Ridículo
3  Vadisnelson     32   7.0   Ridículo
5   Sindicreia     29   5.0   Ridículo

In [18]:
df.rename(columns={'Nota': 'Nota Final'})

Nome  Idade  Nota Final   Situação
0          Ana     23         8.5        Bom
1        Bruno     31         7.2   Ridículo
2        Carla     27         9.1  Excelente
3  Vadisnelson     32         7.0   Ridículo
4  Clebisvaldo     45         8.2        Bom
5   Sindicreia     29         5.0   Ridículo
6    Margarida     18        10.0  Excelente

In [20]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [24]:
df['Nome'].unique
df['Nome'].value_counts()

Nome
Ana            1
Bruno          1
Carla          1
Vadisnelson    1
Clebisvaldo    1
Sindicreia     1
Margarida      1
Name: count, dtype: int64

In [1]:
import pandas as pd

dados = {
    'Nome': ['Walas', 'Marquinhos', 'Alex', 'Daniel', 'Narciso'],
    'Cidade': ['Porto', 'Lisboa', 'Aveiro', 'Porto', 'Porto'],
    'Número de corridas': [25, 20, 15, 23, 5],
    'Nota': [0.5, 6.0, -5.0, 6.3, 10]
    
}

df = pd.DataFrame(dados)

df

Nome  Cidade  Número de corridas  Nota
0       Walas   Porto                  25   0.5
1  Marquinhos  Lisboa                  20   6.0
2        Alex  Aveiro                  15  -5.0
3      Daniel   Porto                  23   6.3
4     Narciso   Porto                   5  10.0

In [2]:
df['Nota'] = df['Nota'].astype(float)

In [3]:
df['Cidade'] = df['Cidade'].astype('category')

In [7]:
df.dtypes

Nome                    object
Cidade                category
Número de corridas       int64
Nota                   float64
dtype: object

In [9]:
df[df['Cidade'] == 'Lisboa']

Nome  Cidade  Número de corridas  Nota
1  Marquinhos  Lisboa                  20   6.0

In [11]:
df['Nota ajustada'] = df['Nota'] + 0.2
df

Nome  Cidade  Número de corridas  Nota  Nota ajustada
0       Walas   Porto                  25   0.5            0.7
1  Marquinhos  Lisboa                  20   6.0            6.2
2        Alex  Aveiro                  15  -5.0           -4.8
3      Daniel   Porto                  23   6.3            6.5
4     Narciso   Porto                   5  10.0           10.2

In [22]:
import numpy as np

condicoes = [
    df['Nota'] >= 9.0,
    (df['Nota'] >= 8.0) & (df['Nota'] < 9.0),
    df['Nota'] < 8.0
]

resultados = ['Excelente', 'Bom', 'Ridículo']

df['Avaliação'] = np.select(condicoes, resultados)
df


Nome  Cidade  Número de corridas  Nota  Nota ajustada  Avaliação
0       Walas   Porto                  25   0.5            0.7   Ridículo
1  Marquinhos  Lisboa                  20   6.0            6.2   Ridículo
2        Alex  Aveiro                  15  -5.0           -4.8   Ridículo
3      Daniel   Porto                  23   6.3            6.5   Ridículo
4     Narciso   Porto                   5  10.0           10.2  Excelente

In [36]:
print('Who')

Who
